Add help to scripts (#7)
* Refactor motivation

* Refactor php-cs-fixer

* Refactor disallow-commits

* Refactor conventional-commit

* Refactor files-watcher

* Make code and help consitent

diff --git a/disallow-commits/disallow-commits b/disallow-commits/disallow-commits
--- a/disallow-commits/disallow-commits
+++ b/disallow-commits/disallow-commits
@@ -27,28 +27,55 @@
 # OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 # EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 # =============================================================================
-# The `pre-commit` hook to disallow commits to some branches.
-# Useful for example to disallow commits directly to master branch.
-# Example of config:
-# ~~~
-# [disallow-commits]
-#   branch = master
-#   branch = development
-# ~~~
 
 FCR='\033[1;31m' # Red
+FCG='\033[1;32m' # Green
+FCY='\033[0;33m' # Yellow
+FCS='\033[0;37m' # Light gray (silver)
 NC='\033[0m'
 
-branch_name="$(git rev-parse --abbrev-ref HEAD)"
-closed_branches=$(git config --get-all disallow-commits.branch)
+CMD="disallow-commits"
+VERSION="1.0.0"
+HOME="https://github.com/slavcodev/git-hooks-scripts"
+ABOUT="${FCG}Branch protection${NC} version ${FCY}$VERSION${NC}"
+HELP="$ABOUT
 
-if [[ -z ${closed_branches} ]]; then
-  closed_branches="master"
-fi
+The 'pre-commit' hook to disallow commits into some branches.
+Useful for example to disallow commits directly to master branch.
 
-for closed_branch in ${closed_branches} ; do
-  if [[ "${branch_name}" =~ "${closed_branch}" ]]; then
-    echo "${FCR}You can't commit directly to ${closed_branch} branch${NC}"
-    exit 1
+Multiple branches are supported.
+
+${FCY}Example of config:${NC}
+${FCS}~~~
+[${CMD}]
+  branch = master
+  branch = development
+~~~${NC}
+
+$HOME
+
+> Enjoy coding ❤️"
+
+main() {
+  branch_name="$(git rev-parse --abbrev-ref HEAD)"
+  closed_branches=$(git config --get-all disallow-commits.branch)
+
+  if [[ -z ${closed_branches} ]]; then
+    closed_branches="master"
   fi
-done
+
+  for closed_branch in ${closed_branches} ; do
+    if [[ "${branch_name}" =~ "${closed_branch}" ]]; then
+      echo "${FCR}You can't commit directly to ${closed_branch} branch${NC}"
+      exit 1
+    fi
+  done
+}
+
+case "$1" in
+  -h|--help|-? )
+    echo "${HELP}"
+    ;;
+  * )
+    main
+esac
